name = "legacy-of-bbs"
compatibility_date = "2022-12-31"

# D1 : SQLite・`binding` がグローバル変数名になる・別途 Web コンソールで「D1 データベース バインディング」(グローバル変数の紐付け) が必要
[[ d1_databases ]]
binding = "DB"
database_name = "legacy-of-bbs"
database_id = "eebf425b-5865-429f-960a-9ab1ea6a0c32"

# シークレット : 本番の環境変数は `$ wrangler secret put CREDENTIAL` コマンドで入力する
[vars]
CREDENTIAL = "test"
