name = "legacy-of-bbs"
compatibility_date = "2022-12-31"
pages_build_output_dir = "./"

# D1 : SQLite・`binding` がグローバル変数名になる・別途 Web コンソールで「D1 データベース バインディング」(グローバル変数の紐付け) が必要
[[d1_databases]]
binding = "DB"
database_name = "legacy-of-bbs-20240716"
database_id = "191d00e6-e2e0-4a68-96ac-6d63f30ca87c"
